trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  azureServiceConnection: 'KnowledgeBaseDevOpsSP'
  location: 'westeurope'

steps:
  - task: AzureCLI@2
    displayName: '(1) Generate Bicep file (workaround)'
    inputs:
      azureSubscription: '$(azureServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'bicep build resourcegroup.bicep'
      workingDirectory: 'infra'
  - task: AzureCLI@2
    displayName: '(3) Deploy Resource Group'
    inputs: 
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az deployment sub create --template-file resourcegroup.json --location $(location)
      workingDirectory: 'infra'
